### ISSUE TITLE
dados pessoais

### ISSUE THREAD

**Issue by joaociocca** [isabellefo/Arquivo-Bancario#1]
não achei meio de contato, então estou abrindo issue... cuidado que vocês estão expondo dados pessoais em dois arquivos deste repositório!

**Comment by gfborges** [comment]
João esses dados são fictícios, para um tarefa de padrões de projeto na faculdade :wink:. Mas obrigado pelo toque

**Comment by joaociocca** [comment]
muito bom, Gabriel! uma dica então pro próximo, façam nomes de bancos fictícios também ;)

**Comment by gfborges** [comment]
Olá,

Pode deixar, percebi que recebemos uma notificação da CSIRT. Se você tem
algo a ver ou um contato peço que entre em contato e conte do mal entedido.

Att,
Gabriel

Em qui., 8 de out. de 2020 às 13:50, João Ciocca <notifications@github.com>
escreveu:

**Comment by gfborges** [comment]
Olá,
Uma correção, a empresa é Tempest Security Intelligence

Att
Gabriel

Em qui., 8 de out. de 2020 às 16:04, Gabriel Borges <
gabrielfr.borges@gmail.com> escreveu:

**Comment by joaociocca** [comment]
eu ia corrigir isso. "CSIRT" são os times de resposta a incidentes de segurança.
Provavelmente algum cliente da Tempest acionou eles pensando no mesmo caso que eu. Responda à notificação deles diretamente, explicando se tratar de massa de dados fictícia, onde apenas os nomes dos bancos reais foi utilizado, que deve ficar tudo bem =)
